[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"  # Replace with your actual build folder

[context.production.environment]
  NODE_VERSION = "17.9.1"  # Use the Node version from your logs or adjust accordingly
